version: "3.3"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL:-database}
      CACHE_URL: ${CACHE_URL:-cache}
#      DEBUG: 'True'
  database:
    ports:
      - 27017:27017
    image: mongo
  cache:
    ports:
      - 6379:6379
    image: redis
